[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--force"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
