FROM python:3.10.17-slim

RUN pip install --no-cache-dir fastapi uvicorn pandas requests

RUN mkdir -p /app/predikcija

WORKDIR /app

VOLUME ["/tmp"]

COPY predikcija_helper/ .

EXPOSE 47869

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "47869"]