name: publish and deploy
on:
  push:
    branches:
      - '**'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t adam8kac/omreznina-app:latest -f ./docker/Dockerfile .
      - name: push image
        run: |
          docker login -u adam8kac -p ${{ secrets.DOCKER_TOKEN }} \
          docker push adam8kac/omreznina-app:latest \
